### PR TITLE
fix clang-tools

### LINKED ISSUE #18240: [Bug]: Clang-tidy dosent find headers properly
### Problem description

Hi, i have noticed that clang-tidy isnt working as it should because it errors out with it weirdly not finding headers while clang does that properly with no issue.
The error in question (in a simple c file, it varies depending on what you try to include) is: 

`
Error while processing /data/data/com.termux/files/home/test.c.
/data/data/com.termux/files/usr/include/sys/types.h:32:10: error: 'stddef.h' file not found [clang-diagnostic-error]
   32 | #include <stddef.h>
      |          ^~~~~~~~~~
`

### What steps will reproduce the bug?

just run clang-tidy, on a c++/c file, i tested it for example on a simple c file:
`
#include <stdio.h>
int main() {
  puts("Test");
  return 0;
}  ` 
It errored out while clang compiled it fine.

### What is the expected behavior?

For it to not exit because of weird header errors.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=11885
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.39.1
Android version:
9
Kernel build information:
Linux localhost 4.9<REDACTED> #1 SMP PREEMPT Tue Jun <REDACTED> armv8l Android
Device manufacturer:
<REDACTED>
Device model:
<REDACTED>
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
com.termux.window versionCode:15
```

### PR DESCRIPTION
**Pull request by landfillbaby**
the llvm codebase is confusing but i think this fixes #18240 which was caused by #18074. needs testing when ci is done.

### CODE REVIEW

**Comment by landfillbaby** [comment]
... i maybe got the wrong part of the right file. if it doesn't work, this is the fix instead. it even says so in the comment

```diff
--- a/clang/lib/Tooling/Tooling.cpp
+++ b/clang/lib/Tooling/Tooling.cpp
@@ -600,7 +600,7 @@ int ClangTool::run(ToolAction *Action) {
       // FIXME: On linux, GetMainExecutable is independent of the value of the
       // first argument, thus allowing ClangTool and runToolOnCode to just
       // pass in made-up names here. Make sure this works on other platforms.
-      injectResourceDir(CommandLine, "clang_tool", &StaticSymbol);
+      injectResourceDir(CommandLine, "clang", &StaticSymbol);
 
       // FIXME: We need a callback mechanism for the tool writer to output a
       // customized message for each file.
```

**Comment by landfillbaby** [comment]
ok this way works but i just thought of a better one i think. https://github.com/llvm/llvm-project/blob/llvmorg-17.0.2/llvm/lib/Support/Unix/Path.inc#L320

**Comment by landfillbaby** [comment]
ok, i think this is closer to the way it would have worked without having to patch everything that calls it indirectly because they haven't actually bothered to test it on non-linux oses

**Comment by landfillbaby** [comment]
wait i can do even better! brb parsing /proc/self/cmdline

**Comment by landfillbaby** [comment]
ok now it's nearly perfect :)

**Comment by landfillbaby** [comment]
i guess this will be how we fix all of the programs that need their own absolute path :)
