### PR TITLE
nodejs: Update from 13.0.0 to 13.13.0

### PR DESCRIPTION
**Pull request by fornwall**
Currently does not build, the

    g++ -rdynamic -m64 -fPIC  -o /home/builder/.termux-build/nodejs/src/out/Release/mksnapshot [..]

command fails with:

```
/usr/bin/ld: /home/builder/.termux-build/nodejs/src/out/Release/obj.host/v8_compiler/deps/v8/src/compiler/wasm-compiler.o: in function `v8::internal::compiler::CompileWasmMathIntrinsic(v8::internal::wasm::WasmEngine*, v8::internal::compiler::WasmImportCallKind, v8::internal::Signature<v8::internal::wasm::ValueType>*)':
wasm-compiler.cc:(.text._ZN2v88internal8compiler24CompileWasmMathIntrinsicEPNS0_4wasm10WasmEngineENS1_18WasmImportCallKindEPNS0_9SignatureINS2_9ValueTypeEEE+0xf1): undefined reference to `v8::internal::compiler::InstructionSelector::SupportedMachineOperatorFlags()'
/usr/bin/ld: wasm-compiler.cc:(.text._ZN2v88internal8compiler24CompileWasmMathIntrinsicEPNS0_4wasm10WasmEngineENS1_18WasmImportCallKindEPNS0_9SignatureINS2_9ValueTypeEEE+0xf9): undefined reference to `v8::internal::compiler::InstructionSelector::AlignmentRequirements()'
[...]
```

Full build output at: https://gist.githubusercontent.com/fornwall/97f40249c718e55e6de162763fe2d6d5/raw/89db0b03b39ccff89e78eefa9b5cd8bf8815625e/error-output.txt

### CODE REVIEW

**Comment by fornwall** [comment]
Version 13.0.1 of node.js dropped support for building without snapshot:
https://github.com/nodejs/node/pull/30021

**Comment by talentlessguy** [comment]
While there is 13.7 already, Termux still has 13.0

any plans on updating it? :)

**Comment by danielo515** [comment]
13 is not the stable version. Why do you want to use it?

**Comment by Grimler91** [comment]
All arches except x86_64 seem to build fine with 13.12.0

**Comment by fornwall** [comment]
@Grimler91 Nice! Blacklisted x86_64 for now and merged this.
