### ISSUE TITLE
[Package]: anki

### ISSUE THREAD

**Issue by sudomain** [termux/termux-packages#14693]
### Why do you want to add this package to Termux?

Anki is a flashcard program for learning information.

### Home page URL

https://apps.ankiweb.net/

### Source code URL

https://github.com/ankitects/anki/

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

[Someone else is attempting to build from source](https://github.com/termux/termux-packages/issues/8029#issuecomment-1398631744). I've tried to install via [pip for Linux (ARM)](https://betas.ankiweb.net/#via-pypipip) but a `pyenv/bin/anki` file doesn't get created and there's no errors if all dependencies are installed: `pkg in portaudio qt5-qtwebengine qt5-qtmultimedia python-pyqtwebengine`

**Comment by xtkoba** [comment]
The latest version, 2.1.56, seems to be rather difficult to package. Does some older version, e.g. 2.1.15 (which is packaged by Gentoo Portage) satisfy your needs?

**Comment by sudomain** [comment]
Unfortunately that's a rather outdated version and I can get a more recent version by installing via pip in a Debian PRoot, though it is a PRoot so performance isn't great. Additionally ARM64 support [wasn't added (experimentally) until 2.1.39](https://betas.ankiweb.net/older.html?highlight=Arm#changes-in-2139beta1).

Do you have any suggestions for installing via the python wheel? Pip seems to get all of the modules it needs but silently fails to create the executable

**Comment by xtkoba** [comment]
2.1.15 is a platform-independent pre-Rust version.

Current version (2.1.56) adopts some peculiar build system which is invoked within Cargo build system and as of now I have no idea how to adapt it to our packaging system.

**Comment by xtkoba** [comment]
Disclaimer: Dependency on `portaudio` suggests this software expects some audio output, which however will NOT work as of now. Does this satisfy your needs even then?

**Comment by sudomain** [comment]
Understood about the build system. It would support my personal needs without audio, but a decent number of Anki users use it to learn foreign languages. Many of them add audio files to their flashcards to learn pronunciation of words. Would portaudio not work if we have a pulseaudio daemon running?

**Comment by xtkoba** [comment]
Vanilla PortAudio does not support PulseAudio. A certain third party repo did package `portaudio` with PulseAudio support added, but it was not contributed to our official repo, unfortunately.

FYI, older version of Anki such as version 2.1.15 relied on `mpv` for audio playback, which will work on Termux now.

**Comment by krmanik** [comment]
I'm working on it (anki 2.1.56), building it for termux, it requires following things, which may not be easy to build for official termux repository. But it will/may be available in tur-repo (code server available here).

Requires
1. python3.9 (only in tur-repo, official repo contains 3.11 now)
2. I have tested rust 1.64.0 and 1.66.1 versions to build anki and anki is not running, I will now test 1.65.0 version.
          a) Anki build on rust version 1.66.1 shows these errors,
              `ImportError: dlopen failed: cannot find symbol '__extenddftf2' referenced by '/data/data/com.termux/files/home/anki/out/rust/debug/librsbridge.so'...`
          b) Anki build on rust version 1.64.0 shows `segmentation fault`

Need these patches
1. protoc and nodejs in the path similar to `PYTHON_BINARY` because the downloaded binaries used in the build process are not running, I have created a patch for protoc and working on nodejs.
https://gist.github.com/krmanik/ca91c0e459be729e956da7671beca23e
2. Change the system site-packages to true in python virtual pyenv in `out` dir.

I know how to compile but do not how to package but it can be packaged because PyQtWebEngine is python wheel and packaged for termux so I think anki python wheel can also be packaged.

**Comment by krmanik** [comment]
How the errors can be fixed?
```
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/rustczMVfu4/symbols.o" ....
 = note: ld: error: /data/data/com.termux/files/usr/lib/liblzma.so is incompatible with elf64-x86-64
          collect2: error: ld returned 1 exit status
```

This is build.sh and anki patch file. View [anki.patch](https://gist.github.com/krmanik/e7414aa83edfd41a844626a6c36f27d9) file.
```sh
TERMUX_PKG_HOMEPAGE=https://apps.ankiweb.net/
TERMUX_PKG_DESCRIPTION="Anki is a spaced repetition system (SRS), a program which allows you to create, manage and review flashcards."
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=2.1.57rc2
_COMMIT=6b7d372ca995b728f467d63ab14495f0ce346258
TERMUX_PKG_SRCURL=git+https://github.com/ankitects/anki
TERMUX_PKG_GIT_BRANCH=main
TERMUX_PKG_DEPENDS="pyqt5, python-pyqtwebengine"
TERMUX_PKG_BUILD_DEPENDS="binutils, curl, git, grep, findutils, ninja, nodejs-lts, protobuf, python, pyqt5, python-pyqtwebengine, rust, rsync"
TERMUX_PKG_PYTHON_TARGET_DEPS="pip-tools"
TERMUX_PKG_BUILD_IN_SRC=true

termux_step_pre_configure() {
	export RUSTFLAGS+=" -C lto=no"
	#export CARGO_BUILD_TARGET=${CARGO_TARGET_NAME}
}

termux_step_post_get_source() {
	git fetch
	git checkout $_COMMIT
	git submodule update --recursive
}

termux_step_make() {
	termux_setup_rust
	termux_setup_ninja
	termux_setup_protobuf
	termux_setup_nodejs

	export NODE_BINARY=$(command -v node)
	export PROTOC_BINARY=$(command -v protoc)
	export PYTHON_BINARY=python
	export PYTHONPATH=$TERMUX_PYTHON_HOME/site-packages
	./tools/build
}

termux_step_make_install() {
	pip install out/wheels/*.whl
}
```

**Comment by xtkoba** [comment]
@krmanik Please refrain from posting `build.sh` here in Issues. Submit a PR instead. Thanks.

**Comment by new-c0der-1** [comment]
Can anyone check where is the issue? Tried to build but getting `exec format error`.

x11-packages/anki/build.sh

```sh
TERMUX_PKG_HOMEPAGE=https://apps.ankiweb.net/
TERMUX_PKG_DESCRIPTION="Anki is a spaced repetition system (SRS), a program which allows you to create, manage and review flashcards."
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=2.1.66
_COMMIT=7d2ec8ed65df450b015156ee93fcc4f8561ab70f
TERMUX_PKG_SRCURL=git+https://github.com/ankitects/anki
TERMUX_PKG_GIT_BRANCH=main
TERMUX_PKG_DEPENDS="pyqt5, python-pyqtwebengine"
TERMUX_PKG_BUILD_DEPENDS="binutils, curl, git, grep, findutils, ninja, nodejs-lts, protobuf, python, pyqt5, python-pyqtwebengine, rust, rsync"
TERMUX_PKG_PYTHON_TARGET_DEPS="pip-tools"
TERMUX_PKG_BUILD_IN_SRC=true

termux_step_post_get_source() {
    git fetch --unshallow
    git submodule update --init --recursive
    git pull --recurse-submodules=true
    git checkout $_COMMIT
    git submodule update --recursive
}

termux_step_make() {
        CARGO_TARGET_NAME=$TERMUX_ARCH-linux-android
        echo $CARGO_TARGET_NAME

        termux_setup_rust
        termux_setup_ninja
        termux_setup_protobuf
        termux_setup_nodejs

        export RUSTFLAGS+=" -C lto=no"
        export CARGO_BUILD_TARGET=$CARGO_TARGET_NAME

        export NODE_BINARY=$(command -v node)
        export PROTOC_BINARY=$(command -v protoc)
        export PYTHON_BINARY=$(command -v python3)
        export YARN_BINARY=$(command -v yarn)
        export PYTHONPATH=$TERMUX_PYTHON_HOME/site-packages
        export TERMUX_ELF_CLEANER="$(command -v termux-elf-cleaner)"

        export RELEASE=1
        export out=$(pwd)/out
        export CARGO_TARGET_DIR=$out/rust
        cargo build --target=aarch64-linux-android -p runner --release
        # cargo build -p runner --release
        # $TERMUX_ELF_CLEANER out/rust/aarch64-linux-android/release/runner
	# ./out/rust/aarch64-linux-android/release/runner build -- $*
        cross run --target aarch64-linux-android out/rust/aarch64-linux-android/release/runner build -- $*
}

termux_step_make_install() {
    pip install out/wheels/*.whl
}
```
