### PR TITLE
Add package: hashcat

### PR DESCRIPTION
**Pull request by Auxilus**

### CODE REVIEW

File: packages/hashcat/Makefile.patch [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
++DEBUG                   := 1
+ PRODUCTION              := 1
+ 
+ ##
+@@ -44,7 +44,7 @@
+ ##
+ 
+ DESTDIR                 ?=
+-PREFIX                  ?= /usr/local
++PREFIX                  ?= /data/data/com.termux/files/usr
```
Comment (Grimler91) [inline packages/hashcat/Makefile.patch]: You could write @TERMUX_PREFIX@ instead of /data/data/com.termux/files/usr, build-package.sh automatically sed's it.

File: packages/hashcat/Makefile.patch [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+ 
+ INSTALL_FOLDER          ?= $(PREFIX)/bin
+ LIBRARY_FOLDER          ?= $(PREFIX)/lib
+@@ -108,7 +108,7 @@
+ CC_WIN_32               := i686-w64-mingw32-gcc
+ CC_WIN_64               := x86_64-w64-mingw32-gcc
+ 
+-## To compile win-iconv with mingw clone from here: https://github.com/win-iconv/win-iconv
++## To compile win-iconv with mingw clone from here: httpsi://github.com/win-iconv/win-iconv
```
Comment (Grimler91) [inline packages/hashcat/Makefile.patch]: httpsi?

File: packages/hashcat/build.sh [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+TERMUX_PKG_SHA256=05a87eb018507b24afca970081f067e64441460319fb75ca1e64c4a1f322b80b
+TERMUX_PKG_SRCURL=https://github.com/hashcat/hashcat/archive/v${TERMUX_PKG_VERSION}.tar.gz
+TERMUX_PKG_BUILD_IN_SRC=yes
+
+
+termux_step_post_configure () {
+
+	mkdir -p $TERMUX_PREFIX/include/CL
+	curl -L https://raw.githubusercontent.com/KhronosGroup/OpenCL-Headers/master/opencl11/CL/cl.h -o $TERMUX_PREFIX/include/CL
+	curl -L https://raw.githubusercontent.com/KhronosGroup/OpenCL-Headers/master/opencl11/CL/cl_platform.h -o $TERMUX_PREFIX/include/C
```
Comment (Grimler91) [inline packages/hashcat/build.sh]: missing L on the end I guess

Comment (Grimler91) [reply packages/hashcat/build.sh]: You could add those files as patches as well with `diff -u -r /dev/null ../cl.h`. 
Probably not good to curl them as the content could change.

File: packages/hashcat/Makefile.patch (hunk 1 above)
Comment (Auxilus) [reply packages/hashcat/Makefile.patch]: `@` should be there ri8?

File: packages/hashcat/build.sh (hunk 3 above)
Comment (Auxilus) [reply packages/hashcat/build.sh]: okay  👍

File: packages/hashcat/Makefile.patch (hunk 1 above)
Comment (Grimler91) [reply packages/hashcat/Makefile.patch]: Yeah, see for example: https://github.com/termux/termux-packages/blob/master/packages/moria/source-config.h.patch

File: packages/hashcat/build.sh (hunk 3 above)
Comment (Auxilus) [reply packages/hashcat/build.sh]: should I create the patch with `diff - u - r $PREFIX/include/CL/cl. h`  >. cl. h. patch `?

Comment (Auxilus) [reply packages/hashcat/build.sh]: cz the patches should go in $PREFIX/include/CL

**Comment by Auxilus** [comment]
@Grimler91 Thanks for the review

**Comment by Auxilus** [comment]
what went wrong??

**Comment by xeffyr** [comment]
@Auxilus patch for makefile is malformed, did you edit or created it by hand ?

**Comment by Auxilus** [comment]
I had to change prefix path to `@TERMUX_PREFIX@`

**Comment by Auxilus** [comment]
should I create a new patch?

**Comment by xeffyr** [comment]
You should create a new patch by running ```diff -uNr {old_sources} {new_sources}```.

**Comment by Auxilus** [comment]
on it..

**Comment by Auxilus** [comment]
@xeffyr Thanks!

**Comment by Auxilus** [comment]
The error is
```
cc1: error: argument to ‘-O’ should be a non-negative integer, ‘g’, ‘s’ or ‘fast’
```

**Comment by xeffyr** [comment]
This is because CFLAGS or similar variable have flag '-Oz', should be changed to '-O2' or removed (because -O2 is already passed).

**Comment by Auxilus** [comment]
same error

**Comment by xeffyr** [comment]
You have changed CC under ```ifeq ($(UNAME),FreeBSD)```.

Try this patch
```
diff -uNr hashcat-4.0.0/src/Makefile hashcat-4.0.0.mod/src/Makefile
--- hashcat-4.0.0/src/Makefile	2017-11-09 16:27:03.850917298 +0200
+++ hashcat-4.0.0.mod/src/Makefile	2017-11-09 16:26:42.750700840 +0200
@@ -80,7 +80,7 @@
 ## Native compiler paths
 ##
 
-CC                      ?= gcc
+CC                      := gcc
 FIND                    := find
 INSTALL                 := install
 RM                      := rm
```

**Comment by xeffyr** [comment]
Sorry, patch should be this:
```
diff -uNr hashcat-4.0.0/src/Makefile hashcat-4.0.0.mod/src/Makefile
--- hashcat-4.0.0/src/Makefile	2017-11-09 17:31:23.279752524 +0200
+++ hashcat-4.0.0.mod/src/Makefile	2017-11-09 17:31:50.830036781 +0200
@@ -80,7 +80,7 @@
 ## Native compiler paths
 ##
 
-CC                      := gcc
+CC                      ?= gcc
 FIND                    := find
 INSTALL                 := install
 RM                      := rm
```

**Comment by Auxilus** [comment]
Np, I figured that out 😅

**Comment by xeffyr** [comment]
To fix error about iconv.h:
```
CFLAGS += -I@TERMUX_PREFIX@/include
```

And libandroid-support should be added as dependency to build.sh

**Comment by xeffyr** [comment]
But OpenCL is not working.

**Comment by Auxilus** [comment]
openCL might not work as I'm just adding headers..

**Comment by Auxilus** [comment]
I missed some' ?

**Comment by Grimler91** [comment]
Missing dependency on iconv I guess

**Comment by Auxilus** [comment]
I've added `libandroid-support-dev` as dependency cz it includes `iconv.h`

**Comment by xeffyr** [comment]
@Auxilus, you wrote ```openCL might not work as I'm just adding headers```, this means that hashcat won't work at all because all latest versions require OpenCL.

Only hashcat-legacy can work without OpenCL.

**Comment by Auxilus** [comment]
I must've said wrong thing...

**Comment by Auxilus** [comment]
screenshot_20171110-072813

**Comment by Auxilus** [comment]
still getting `iconv.h not found error`

**Comment by xeffyr** [comment]
To fix iconv.h add to Makefile.patch:
```
CFLAGS += -I@TERMUX_PREFIX@/include
```
To fix error about pthread, remove this line (in Termux, libpthread is a symlink to libc):
```
LFLAGS_NATIVE           += -lpthread
```

**Comment by Auxilus** [comment]
@xeffyr Thanks!

**Comment by xeffyr** [comment]
Hashcat builds sucessfully, but still not working on my device:
```
hashcat (v4.0.0) starting...

clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR
```

**Comment by Auxilus** [comment]
Maybe problem with your device? have you tried on o
screenshot_20171110-163615
ther devices? cz I'm getting no errors with openCL

**Comment by xeffyr** [comment]
Android 7.0, OpenCL supported and library for it is present. What GPU on your device ?

**Comment by xeffyr** [comment]
On my device GPU is Mali. There is a possibility that OpenCL headers is incompatible with mali driver.

**Comment by Auxilus** [comment]
AdrenoTM 430

**Comment by Auxilus** [comment]
@xeffyr Can you please share deb file for all architectures?

**Comment by xeffyr** [comment]
Yes, I can.

Also I have checked my device with program OpenCL-Z and it looks like that OpenCL is working:
screenshot_20171110-135506

**Comment by Auxilus** [comment]
If you could send me deb files, I would be able to test them on some devices...

**Comment by xeffyr** [comment]
Im building them

**Comment by xeffyr** [comment]
[hashcat_debs.zip](https://github.com/termux/termux-packages/files/1461226/hashcat_debs.zip)
- only for aarch64. On other architectures build fails.

**Comment by Auxilus** [comment]
any idea why they fail?
Ty for the deb file...

**Comment by Auxilus** [comment]
debfile seems to work 
screenshot_20171110-174426

**Comment by xeffyr** [comment]
On Qualcomm devices it works, so we need to test it on different devices.

**Comment by xeffyr** [comment]
When compiling hashcat to different architectures error is:

ARM:
```
In file included from src/hashes.c:7:
include/types.h:716:16: error: redefinition of 'user'
typedef struct user
               ^
/home/builder/.termux-build/_lib/15.2-arm-21-v14/bin/../sysroot/usr/include/sys/user.h:223:8: note: previous definition is here
struct user {
       ^
In file included from src/dictstat.c:7:
include/types.h:716:16: error: redefinition of 'user'
typedef struct user
               ^
/home/builder/.termux-build/_lib/15.2-arm-21-v14/bin/../sysroot/usr/include/sys/user.h:223:8: note: previous definition is here
struct user {
       ^
In file included from src/bitops.c:7:
include/types.h:716:16: error: redefinition of 'user'
typedef struct user
```

i686:
```
In file included from src/loopback.c:7:
include/types.h:716:16: error: redefinition of 'user'
typedef struct user
               ^
/home/builder/.termux-build/_lib/15.2-i686-21-v14/bin/../sysroot/usr/include/sys/user.h:87:8: note: previous definition is here
struct user {
       ^
In file included from src/ext_OpenCL.c:7:
include/types.h:716:16: error: redefinition of 'user'
typedef struct user
               ^
/home/builder/.termux-build/_lib/15.2-i686-21-v14/bin/../sysroot/usr/include/sys/user.h:87:8: note: previous definition is here
struct user {
       ^
In file included from In file included from src/cpu_crc32.c:7:
include/types.h:716:16: error: redefinition of 'user'
typedef struct user
               ^
/home/builder/.termux-build/_lib/15.2-i686-21-v14/bin/../sysroot/usr/include/sys/user.h:87:8: note: previous definition is here
struct user {
       ^
src/cpt.c:7:
include/types.h:716:16: error: redefinition of 'user'
typedef struct user
```

**Comment by Auxilus** [comment]
Any idea how to fix 'em?

**Comment by xeffyr** [comment]
I have fixed it. Patch: [types.h.patch.txt](https://github.com/termux/termux-packages/files/1461432/types.h.patch.txt)

**Comment by Auxilus** [comment]
ty! Ive pushed commit

**Comment by Auxilus** [comment]
kindly share deb files

**Comment by xeffyr** [comment]
Yesterday reverted back to rooted Android 6.0.1 (from stock 7.0) - and now hashcat works.

So there is a questions:<br>1. Is SELinux can restrict usage of OpenCL ?
2. Or on Android 7 we need a special permissions to use OpenCL ?

**Comment by Droid-MAX** [comment]
I got the same problem, hashcat can not work properly! Tip is OpenCL problem.

**Comment by xeffyr** [comment]
@Droid-MAX, I got it working on Android 6.0 but it was rooted and selinux-permissive. On fully official 7.0 it not working (no root & selinux-enforce). So I guess that this may not be an OpenCL's problem.

**Comment by Auxilus** [comment]
I'm on 6.0.1, hashcat works well on my device

**Comment by Droid-MAX** [comment]
screenshot_20180227-000743

**Comment by Droid-MAX** [comment]
My phone is Nexus 5 , and I execute setenforce 0 in root permission at first, but still not working.

**Comment by Droid-MAX** [comment]
screenshot_20180227-013433

OpenCL look like working properly, but there have some header file missed.

**Comment by huitc** [comment]
Who can provide detailed teaching to me t.t

**Comment by xeffyr** [comment]
@huitc You are another script kiddy that want an _universal magickal tools_ for hacking ? If not, - you should have already been teached.
**Don't spam here !** For such questions you have Internet (google, irc, etc...).

**Comment by Droid-MAX** [comment]
Platform Version: Android 5.1 aarch64
SELinux Status: Permissive
GPU Model: Mali-T720 MP2
BUG Report:
When I run "hashcat -I" command, I got an Error Output: "clGetPlatformIDs():CL_PLATFORM_NOT_FOUND_KHR"

Is it necessary to manually compile the opencl driver for the Mali-T720 chip?

**Comment by xeffyr** [comment]
@Droid-MAX My device by default has OpenCL driver.

**Comment by Droid-MAX** [comment]
@xeffyr Is it necessary to update the system?

**Comment by Droid-MAX** [comment]
I found libGLES_mali.so in my system, but I don't know how to use it on the hashcat.

**Comment by xeffyr** [comment]
@Droid-MAX Do you have /vendor/lib64/libOpenCL.so ?

**Comment by vishalbiswas** [comment]
@Droid-MAX that is OpenGL ES Driver. You need OpenCL driver.
Use OpenCL-Z android app yo check whether you have it.

**Comment by Droid-MAX** [comment]
It's been stuck at "Initializing device kernel and memory...".

**Comment by Droid-MAX** [comment]
Oddly enough, I can't find libOpenCL.so in my Nexus5, using the official Android 6.0.1 system.

**Comment by xeffyr** [comment]
Package is now available in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install hashcat
```

**Note**: package works only on specific devices/roms, for example it worked fine on Samsung Galaxy S7 with Android 6 but not working after upgrading to Android 7 and higher.

**Comment by huitc** [comment]
```
$ hashcat --version
v4.0.0
```
wtf!?

**Comment by huitc** [comment]
@xeffyr

**Comment by talybin** [comment]
> OpenCL look like working properly, but there have some header file missed.

In my case build options failed on local include of OpenCL (-I OpenCL). I came up with 3 solutions:

1. Create a symlink to OpenCL directory where you attend to run hashcat, e.g. `ln -s ~/../usr/share/hashcat/OpenCL .`
2. Download sources from [github](https://github.com/hashcat/hashcat) and run hashcat from downloaded directory. No compile needed since only OpenCL directory needed.
3. Download sources from [github](https://github.com/hashcat/hashcat). Locate and remove any occurrences of `-I OpenCL`. Build and install.

**Comment by xeffyr** [comment]
@talybin Hashcat is already in unstable-packages: https://github.com/termux/unstable-packages/tree/master/packages/hashcat.

**Comment by xb3b6** [comment]
> @talybin Hashcat уже находится в нестабильных пакетах: https://github.com/termux/unstable-packages/tree/master/packages/hashcat .

No (404)

**Comment by xeffyr** [comment]
@xb3b6 It was, but I have removed it. No hashcats and other cracks anymore: https://wiki.termux.com/wiki/Hacking.
