### PR TITLE
asciinema: remove failing nl_langinfo check

### LINKED ISSUE #3172: asciinema doesn't work with Python3.7
Run `asciinema rec`
Get:
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/asciinema", line 11, in <module>
    load_entry_point('asciinema==2.0.1', 'console_scripts', 'asciinema')()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/asciinema-2.0.1-py3.7.egg/asciinema/__main__.py", line 53, in main
AttributeError: module 'locale' has no attribute 'nl_langinfo'
```

### PR DESCRIPTION
**Pull request by Grimler91**
Fixes #3172

### CODE REVIEW

**Comment by fornwall** [comment]
Thanks, the updated package is now available for installation!
