### ISSUE TITLE
asciinema doesn't work with Python3.7

### ISSUE THREAD

**Issue by edward-p** [termux/termux-packages#3172]
Run `asciinema rec`
Get:
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/asciinema", line 11, in <module>
    load_entry_point('asciinema==2.0.1', 'console_scripts', 'asciinema')()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/asciinema-2.0.1-py3.7.egg/asciinema/__main__.py", line 53, in main
AttributeError: module 'locale' has no attribute 'nl_langinfo'
```

**Comment by fornwall** [comment]
This has now been fixed in version `2.0.1-2` of the asciinema package - run `pkg up` to update.

Thanks for reporting!

Note that Ctrl+D to end the recording may not work (https://github.com/asciinema/asciinema/issues/295), so use `exit` to end the recording.
